// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO-cBZtdC0Z-nARLaRNrko9k-g-QMepus',
    appId: '1:597085939959:web:7ad61592d3e5ccef738bf2',
    messagingSenderId: '597085939959',
    projectId: 'sudoku-9ee4c',
    authDomain: 'sudoku-9ee4c.firebaseapp.com',
    storageBucket: 'sudoku-9ee4c.firebasestorage.app',
    measurementId: 'G-T5LCHC9XBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26oei2SwiqwvF8h70ZUdWS3X28EL_FOI',
    appId: '1:597085939959:android:69d032dc387ab816738bf2',
    messagingSenderId: '597085939959',
    projectId: 'sudoku-9ee4c',
    storageBucket: 'sudoku-9ee4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYP44SGKgJmAH81UfTPOXNFVaoxEU0rQ',
    appId: '1:597085939959:ios:c553b73382ada5b9738bf2',
    messagingSenderId: '597085939959',
    projectId: 'sudoku-9ee4c',
    storageBucket: 'sudoku-9ee4c.firebasestorage.app',
    iosBundleId: 'com.example.sudoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOYP44SGKgJmAH81UfTPOXNFVaoxEU0rQ',
    appId: '1:597085939959:ios:c553b73382ada5b9738bf2',
    messagingSenderId: '597085939959',
    projectId: 'sudoku-9ee4c',
    storageBucket: 'sudoku-9ee4c.firebasestorage.app',
    iosBundleId: 'com.example.sudoku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO-cBZtdC0Z-nARLaRNrko9k-g-QMepus',
    appId: '1:597085939959:web:a9781b102afcc8cd738bf2',
    messagingSenderId: '597085939959',
    projectId: 'sudoku-9ee4c',
    authDomain: 'sudoku-9ee4c.firebaseapp.com',
    storageBucket: 'sudoku-9ee4c.firebasestorage.app',
    measurementId: 'G-FMBXPYQ4NB',
  );
}
